### ISSUE TITLE
Update README with usage

### ISSUE THREAD

**Issue by toymachiner62** [renard/mysql-backup#6]
This repo looks super awesome after checking out the source code itself, but for dummies like me, it'd be nice if your readme had at least some simple instructions on how to use this.

I'm assuming that I just copy your main script and then have a cron job set to run it whenever i'd like a backup made?

**Comment by renard** [comment]
Yes that's pretty it.

Your `crontab`  looks like:

```
MAILTO=user@example.com

PATH=/usr/sbin:/usr/bin:/sbin:/bin

1 0 * * * /usr/local/bin/mysql-backup -c /etc/mysql-backup/mysql-backup.cnf --snapshot
```

And your `/etc/mysql-backup/mysql-backup.cnf` like (assuming you are using mysql on Debian):

```
BACKUP_DIR=/var/backups/mysql
IGNORE_DATABASES=("information_schema" "performance_schema")
TARGET_MOUNT=/tmp/db_00-bck
LVM_SNAPSHOT_SIZE="100G"
COMPRESSION="gzip"
COMPRESSION_OPTS=""

defaults_file=$_MYSQL_CONFIG_DIR/my.cnf
defaults_extra_file="$_MYSQL_CONFIG_DIR/debian.cnf"
my_print_defaults_opts=" -e $defaults_file mysqld"
proto=SOCKET
mysqladmin_extra_file="$defaults_extra_file"
proto=SOCKET
```
